export const SET_TOKEN = 'SET_TOKEN'
export const REMOVE_TOKEN = 'REMOVE_TOKEN'
export const SET_IDENTIFIER = 'SET_IDENTIFIER'

export const ADD_MENUS = 'ADD_MENUS'
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
export const SET_DEFAULT_ACTIVE = 'SET_DEFAULT_ACTIVE'
